[[redirects]]
  from = "/api/*"
  to = "http://213.171.6.128:80/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Content-Security-Policy = "upgrade-insecure-requests"}